# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 17:50
from __future__ import unicode_literals

import data.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField(default=data.models.get_now)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512, verbose_name=b'Filename')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], default=0)),
                ('street_num', models.CharField(max_length=64, null=True, verbose_name=b'Street #')),
                ('street_nam', models.CharField(max_length=512, null=True, verbose_name=b'Street name')),
                ('city', models.CharField(max_length=512, null=True, verbose_name=b'City')),
                ('state', models.CharField(choices=[(b'AL', b'AL'), (b'AK', b'AK'), (b'AZ', b'AZ'), (b'AR', b'AR'), (b'CA', b'CA'), (b'CO', b'CO'), (b'CT', b'CT'), (b'DC', b'DC'), (b'DE', b'DE'), (b'FL', b'FL'), (b'GA', b'GA'), (b'HI', b'HI'), (b'ID', b'ID'), (b'IL', b'IL'), (b'IN', b'IN'), (b'IA', b'IA'), (b'KS', b'KS'), (b'KY', b'KY'), (b'LA', b'LA'), (b'ME', b'ME'), (b'MD', b'MD'), (b'MA', b'MA'), (b'MI', b'MI'), (b'MN', b'MN'), (b'MS', b'MS'), (b'MO', b'MO'), (b'MT', b'MT'), (b'NE', b'NE'), (b'NV', b'NV'), (b'NH', b'NH'), (b'NJ', b'NJ'), (b'NM', b'NM'), (b'NY', b'NY'), (b'NC', b'NC'), (b'ND', b'ND'), (b'OH', b'OH'), (b'OK', b'OK'), (b'OR', b'OR'), (b'PA', b'PA'), (b'RI', b'RI'), (b'SC', b'SC'), (b'SD', b'SD'), (b'TN', b'TN'), (b'TX', b'TX'), (b'UT', b'UT'), (b'VT', b'VT'), (b'VA', b'VA'), (b'WA', b'WA'), (b'WV', b'WV'), (b'WI', b'WI'), (b'WY', b'WY')], max_length=4, null=True, verbose_name=b'State')),
                ('month', models.IntegerField(choices=[(1, b'Jan'), (2, b'Feb'), (3, b'Mar'), (4, b'Apr'), (5, b'May'), (6, b'Jun'), (7, b'Jul'), (8, b'Aug'), (9, b'Sep'), (10, b'Oct'), (11, b'Nov'), (12, b'Dec')], null=True)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], null=True)),
                ('pic_quality', models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The quality of the actual picture is high')),
                ('str_quality', models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The quality of the streets visible in the picture is high')),
                ('pot_holes', models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'5+'), (7, b'N/A')], null=True, verbose_name=b'How many potholes are visible in the picture')),
                ('bui_quality', models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The quality of buildings visible in the picture is high')),
                ('car_quality', models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The quality of the vehicles visible in the picture is high')),
                ('litter', models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The amount of litter visible in the picture is high')),
                ('road_work', models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there signs of road work visible in the picture')),
                ('graffiti', models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Is there graffiti visible in the picture')),
                ('for_sale', models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'There are one or more house for sale signs visible in the picture')),
                ('shoes', models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there shoes on a wire visible in the picture')),
                ('trees', models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there trees and/or large bushes visible in the picture')),
                ('broken_signs', models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there any broken street signs visible in the picture')),
                ('people', models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there people actively covering their faces visible in the picture')),
                ('timestarted', models.DateTimeField(default=data.models.get_now)),
                ('timefinished', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.CharField(max_length=128, verbose_name=b'Wage Rate')),
                ('tutorial', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=28, null=True)),
                ('value', models.IntegerField()),
                ('token', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='worktimer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Task'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
