# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 18:25
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160506_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='timezone',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
