# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 18:28
from __future__ import unicode_literals

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160215_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimer',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
