# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 20:17
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20160215_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
