# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 19:29
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160510_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='timestamp',
            field=models.DateTimeField(default=data.models.get_now_niave),
        ),
    ]
