# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 17:28
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20160215_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='citystate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='street',
        ),
        migrations.AddField(
            model_name='task',
            name='city',
            field=models.CharField(max_length=512, null=True, verbose_name=b'City'),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[(b'AL', b'AL'), (b'AK', b'AK'), (b'AZ', b'AZ'), (b'AR', b'AR'), (b'CA', b'CA'), (b'CO', b'CO'), (b'CT', b'CT'), (b'DC', b'DC'), (b'DE', b'DE'), (b'FL', b'FL'), (b'GA', b'GA'), (b'HI', b'HI'), (b'ID', b'ID'), (b'IL', b'IL'), (b'IN', b'IN'), (b'IA', b'IA'), (b'KS', b'KS'), (b'KY', b'KY'), (b'LA', b'LA'), (b'ME', b'ME'), (b'MD', b'MD'), (b'MA', b'MA'), (b'MI', b'MI'), (b'MN', b'MN'), (b'MS', b'MS'), (b'MO', b'MO'), (b'MT', b'MT'), (b'NE', b'NE'), (b'NV', b'NV'), (b'NH', b'NH'), (b'NJ', b'NJ'), (b'NM', b'NM'), (b'NY', b'NY'), (b'NC', b'NC'), (b'ND', b'ND'), (b'OH', b'OH'), (b'OK', b'OK'), (b'OR', b'OR'), (b'PA', b'PA'), (b'RI', b'RI'), (b'SC', b'SC'), (b'SD', b'SD'), (b'TN', b'TN'), (b'TX', b'TX'), (b'UT', b'UT'), (b'VT', b'VT'), (b'VA', b'VA'), (b'WA', b'WA'), (b'WV', b'WV'), (b'WI', b'WI'), (b'WY', b'WY')], max_length=4, null=True, verbose_name=b'State'),
        ),
        migrations.AddField(
            model_name='task',
            name='street_nam',
            field=models.CharField(max_length=512, null=True, verbose_name=b'Street name'),
        ),
        migrations.AddField(
            model_name='task',
            name='street_num',
            field=models.CharField(max_length=64, null=True, verbose_name=b'Street #'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='trees',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there trees and/or large bushes visible in the picture'),
        ),
    ]
