# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 15:09
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20160216_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimer',
            name='page',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
