# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_worktimer_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='street_num',
        ),
        migrations.AlterField(
            model_name='task',
            name='street_nam',
            field=models.CharField(max_length=512, null=True, verbose_name=b'Street name (and # if available)'),
        ),
    ]
