# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 19:10
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20160203_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='graffiti',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Is there graffiti visible in the picture'),
        ),
        migrations.AlterField(
            model_name='task',
            name='broken_signs',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there any broken street signs visible in the picture'),
        ),
        migrations.AlterField(
            model_name='task',
            name='bui_quality',
            field=models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The quality of buildings visible in the picture is high'),
        ),
        migrations.AlterField(
            model_name='task',
            name='car_quality',
            field=models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The quality of the vehicles visible in the picture is high'),
        ),
        migrations.AlterField(
            model_name='task',
            name='for_sale',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'There are one more house for sale signs visible in the picture'),
        ),
        migrations.AlterField(
            model_name='task',
            name='litter',
            field=models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The amount of litter visible in the picture is high'),
        ),
        migrations.AlterField(
            model_name='task',
            name='people',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there people actively covering their faces visible in the picture'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pic_quality',
            field=models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The quality of the actual picture is high'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pot_holes',
            field=models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'5+'), (7, b'N/A')], null=True, verbose_name=b'How many potholes are visible in the picture'),
        ),
        migrations.AlterField(
            model_name='task',
            name='road_work',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there signs of road work visible in the picture'),
        ),
        migrations.AlterField(
            model_name='task',
            name='shoes',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there shoes on a wire visible in the picture'),
        ),
        migrations.AlterField(
            model_name='task',
            name='str_quality',
            field=models.IntegerField(choices=[(1, b'Strongly Disagree'), (2, b'Disagree'), (3, b'Neither Agree or Disagree'), (4, b'Agree'), (5, b'Strongly Agree'), (6, b'N/A')], null=True, verbose_name=b'The quality of the streets visible in the picture is high'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='trees',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes'), (2, b'N/A')], null=True, verbose_name=b'Are there trees or large bushes visible in the picture'),
        ),
    ]
