# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20160609_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
